In [89]:
import pandas as pd
from datetime import datetime, timedelta
import numpy as np

In [90]:
df = pd.read_csv('/student.csv')
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,NaN,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03
10,64011,ธีระ,NaN,NaN,NaN,3.78,NaN,68.0,NaN,2024-01-07
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24
17,64018,ยุพา,21.0,หญิง,NaN,3.23,161.0,50.0,27.0,2024-01-08
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18
19,64020,ลัดดา,22.0,NaN,Science,3.45,168.0,64.0,23.0,2024-01-06

In [91]:
df = pd.DataFrame(df)

In [92]:
# เพิ่มวันที่ลงทะเบียน (สำหรับ feature engineering)
base_date = datetime(2024, 1, 15)
df['วันที่ลงทะเบียน'] = [base_date + timedelta(days=np.random.randint(-30, 30))for _ in range(20)]

In [93]:
print("="*50)
print("🎯 ข้อมูลหลัก (Master Dataset) ที่จะใช้ตลอดบทเรียน")
print("="*50)
print(df)
print("\n📊 สรุปปัญหาที่พบในข้อมูล:")
print(f"- ค่าหายทั้งหมด: {df.isnull().sum().sum()} ค่า")
print(f"- อายุผิดปกติ: {df[df['อายุ'] > 100]['อายุ'].values if any(df['อายุ'] > 100) else 'ไม่มี'}")
print(f"- GPA ผิดปกติ: {df[(df['GPA'] < 0) | (df['GPA'] > 4)]['GPA'].values if any((df['GPA'] < 0) | (df['GPA'] > 4)) else 'ไม่มี'}")
print(f"- รูปแบบการเขียนคณะ: {df['คณะ'].nunique()} แบบ")
print(f"- รูปแบบการเขียนเพศ: {df['เพศ'].nunique()} แบบ")

==================================================
🎯 ข้อมูลหลัก (Master Dataset) ที่จะใช้ตลอดบทเรียน
==================================================
    รหัสนักศึกษา      ชื่อ   อายุ     เพศ             คณะ   GPA  ส่วนสูง_cm  \
0          64001     สมชาย   20.0     ชาย     วิทยาศาสตร์  3.21       170.0
1          64002    สมหญิง   21.0    หญิง           วิทย์  3.45       165.0
2          64003       NaN    NaN    Male         Science  3.67       175.0
3          64004  สมศักดิ์   22.0       ช  คณะวิทยาศาสตร์ -1.00       168.0
4          64005      สมใจ   19.0       ญ           วิศวะ  3.89       160.0
5          64006     กานต์  150.0     ชาย     Engineering  3.12       172.0
6          64007     กิตติ   21.0    หญิง        วิศวกรรม  4.50       158.0
7          64008      จิรา   20.0       F      ศิลปศาสตร์  2.98       180.0
8          64009    ชนาธิป   23.0       M            Arts  3.34       163.0
9          64010      ดารา   21.0    หญิง           ศิลป์  3.56       167.0
10         64011      ธีระ    NaN     NaN             NaN  3.78         NaN
11         64012       นภา   22.0     ชาย           วิทย์   NaN       171.0
12         64013     บุญมี   20.0    หญิง           วิศวฯ  3.23       169.0
13         64014     ปรีชา   21.0     ชาย    Liberal Arts  3.45       164.0
14         64015     พิมพ์   22.0  Female             Sci  3.67       162.0
15         64016      ภูมิ   19.0       ช     วิทยาศาสตร์  3.89       173.0
16         64017      มานี   20.0       ญ  วิศวกรรมศาสตร์  3.01       166.0
17         64018      ยุพา   21.0    หญิง             NaN  3.23       161.0
18         64019     รัตนา    NaN     ชาย      ศิลปศาสตร์   NaN       174.0
19         64020     ลัดดา   22.0     NaN         Science  3.45       168.0

    น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน
0         65.0                     15.0      2024-01-06
1         58.0                     20.0      2024-01-01
2          NaN                     25.0      2024-01-30
3         70.0                     10.0      2023-12-17
4         52.0                     30.0      2024-01-04
5         75.0                     12.0      2024-01-26
6         48.0                     35.0      2024-02-05
7         82.0                     18.0      2023-12-24
8         55.0                     22.0      2024-02-13
9         60.0                     28.0      2024-01-15
10        68.0                      NaN      2024-01-23
11         NaN                     16.0      2023-12-28
12        72.0                     24.0      2023-12-22
13        54.0                     19.0      2023-12-24
14        56.0                     26.0      2024-02-02
15        78.0                     14.0      2024-01-17
16        62.0                     21.0      2024-01-18
17        50.0                     27.0      2024-01-12
18        76.0                      NaN      2024-01-16
19        64.0                     23.0      2024-02-12

📊 สรุปปัญหาที่พบในข้อมูล:
- ค่าหายทั้งหมด: 15 ค่า
- อายุผิดปกติ: [150.]
- GPA ผิดปกติ: [-1.   4.5]
- รูปแบบการเขียนคณะ: 14 แบบ
- รูปแบบการเขียนเพศ: 8 แบบ

In [94]:
# เก็บสำเนาข้อมูลต้นฉบับ
df_original = df.copy()  # สำคัญ! ใช้ .copy() เพื่อไม่ให้กระทบข้อมูลต้นฉบับ

In [95]:
# วิเคราะห์ข้อมูล df ที่สร้างไว้
print("="*50)
print("📋 ข้อมูลทั่วไปของ Dataset")
print("="*50)
df.info()

print("\n" + "="*50)
print("📊 สถิติเชิงพรรณนา")
print("="*50)
print(df.describe())

# ตรวจสอบค่าหายในแต่ละคอลัมน์
missing_counts = df.isnull().sum()
print("\n❌ ค่าหายในแต่ละคอลัมน์:")
for col, count in missing_counts[missing_counts > 0].items():
    percentage = (count / len(df)) * 100
    print(f"   - {col}: {count} ค่า ({percentage:.1f}%)")

==================================================
📋 ข้อมูลทั่วไปของ Dataset
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   รหัสนักศึกษา             20 non-null     int64
 1   ชื่อ                     19 non-null     object
 2   อายุ                     17 non-null     float64
 3   เพศ                      18 non-null     object
 4   คณะ                      18 non-null     object
 5   GPA                      18 non-null     float64
 6   ส่วนสูง_cm               19 non-null     float64
 7   น้ำหนัก_kg               18 non-null     float64
 8   ชั่วโมงเรียน_ต่อสัปดาห์  18 non-null     float64
 9   วันที่ลงทะเบียน          20 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(5), int64(1), object(3)
memory usage: 1.7+ KB

==================================================
📊 สถิติเชิงพรรณนา
==================================================
       รหัสนักศึกษา        อายุ        GPA  ส่วนสูง_cm  น้ำหนัก_kg  \
count      20.00000   17.000000  18.000000   19.000000   18.000000
mean    64010.50000   28.470588   3.246111  167.684211   63.611111
min     64001.00000   19.000000  -1.000000  158.000000   48.000000
25%     64005.75000   20.000000   3.215000  163.500000   55.250000
50%     64010.50000   21.000000   3.450000  168.000000   63.000000
75%     64015.25000   22.000000   3.670000  171.500000   71.500000
max     64020.00000  150.000000   4.500000  180.000000   82.000000
std         5.91608   31.337114   1.123326    5.706260   10.279270

       ชั่วโมงเรียน_ต่อสัปดาห์      วันที่ลงทะเบียน
count                18.000000                   20
mean                 21.388889  2024-01-14 04:48:00
min                  10.000000  2023-12-17 00:00:00
25%                  16.500000  2023-12-31 00:00:00
50%                  21.500000  2024-01-15 12:00:00
75%                  25.750000  2024-01-27 00:00:00
max                  35.000000  2024-02-13 00:00:00
std                   6.598920                  NaN

❌ ค่าหายในแต่ละคอลัมน์:
   - ชื่อ: 1 ค่า (5.0%)
   - อายุ: 3 ค่า (15.0%)
   - เพศ: 2 ค่า (10.0%)
   - คณะ: 2 ค่า (10.0%)
   - GPA: 2 ค่า (10.0%)
   - ส่วนสูง_cm: 1 ค่า (5.0%)
   - น้ำหนัก_kg: 2 ค่า (10.0%)
   - ชั่วโมงเรียน_ต่อสัปดาห์: 2 ค่า (10.0%)

In [96]:
# แก้ค่าผิดปกติของตัวเลขก่อน (เช่น อายุ > 100, GPA <0 หรือ >4)
df.loc[df['อายุ'] > 100, 'อายุ'] = np.nan
df.loc[(df['GPA'] < 0) | (df['GPA'] > 4), 'GPA'] = np.nan
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-06
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-01-01
2,64003,NaN,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-30
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,NaN,168.0,70.0,10.0,2023-12-17
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-04
5,64006,กานต์,NaN,ชาย,Engineering,3.12,172.0,75.0,12.0,2024-01-26
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,NaN,158.0,48.0,35.0,2024-02-05
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2023-12-24
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-02-13
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-15
10,64011,ธีระ,NaN,NaN,NaN,3.78,NaN,68.0,NaN,2024-01-23
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-28
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-22
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2023-12-24
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-02-02
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-17
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-18
17,64018,ยุพา,21.0,หญิง,NaN,3.23,161.0,50.0,27.0,2024-01-12
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2024-01-16
19,64020,ลัดดา,22.0,NaN,Science,3.45,168.0,64.0,23.0,2024-02-12

In [97]:
# เติม missing ข้อมูลตัวเลขด้วย median
num_cols = ['อายุ', 'GPA', 'ส่วนสูง_cm', 'น้ำหนัก_kg', 'ชั่วโมงเรียน_ต่อสัปดาห์']

for col in num_cols:
    print(f" คอลัมน์: {col}")

# หาแถวที่มี NaN ในคอลัมน์นี้
    missing_rows = df[df[col].isna()]

    print("ก่อนเติมค่า :")
    print(missing_rows[[col]])

    median_val = df[col].median()
    df[col].fillna(median_val, inplace=True)

 # แสดงค่าในแถวที่เคย NaN หลังเติม
    print(f"ค่า median ที่ใช้เติม: {median_val:.2f}")
    print("หลังเติมค่า :")
    print( print(df.loc[missing_rows.index, [col]]))
    print("\n")

 คอลัมน์: อายุ
ก่อนเติมค่า :
    อายุ
2    NaN
5    NaN
10   NaN
18   NaN
ค่า median ที่ใช้เติม: 21.00
หลังเติมค่า :
    อายุ
2   21.0
5   21.0
10  21.0
18  21.0
None


 คอลัมน์: GPA
ก่อนเติมค่า :
    GPA
3   NaN
6   NaN
11  NaN
18  NaN
ค่า median ที่ใช้เติม: 3.45
หลังเติมค่า :
     GPA
3   3.45
6   3.45
11  3.45
18  3.45
None


 คอลัมน์: ส่วนสูง_cm
ก่อนเติมค่า :
    ส่วนสูง_cm
10         NaN
ค่า median ที่ใช้เติม: 168.00
หลังเติมค่า :
    ส่วนสูง_cm
10       168.0
None


 คอลัมน์: น้ำหนัก_kg
ก่อนเติมค่า :
    น้ำหนัก_kg
2          NaN
11         NaN
ค่า median ที่ใช้เติม: 63.00
หลังเติมค่า :
    น้ำหนัก_kg
2         63.0
11        63.0
None


 คอลัมน์: ชั่วโมงเรียน_ต่อสัปดาห์
ก่อนเติมค่า :
    ชั่วโมงเรียน_ต่อสัปดาห์
10                      NaN
18                      NaN
ค่า median ที่ใช้เติม: 21.50
หลังเติมค่า :
    ชั่วโมงเรียน_ต่อสัปดาห์
10                     21.5
18                     21.5
None

/tmp/ipython-input-3205317926.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(median_val, inplace=True)
/tmp/ipython-input-3205317926.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(median_val, inplace=True)
/tmp/ipython-input-3205317926.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(median_val, inplace=True)
/tmp/ipython-input-3205317926.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(median_val, inplace=True)
/tmp/ipython-input-3205317926.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(median_val, inplace=True)

In [98]:
# เติมค่า missing ด้วย mode (ค่าที่เจอบ่อยที่สุด)
cat_cols = ['เพศ', 'คณะ']

for col in cat_cols:
    print(f" คอลัมน์: {col}")

    # แสดงก่อนเติมค่า (เฉพาะแถวที่ NaN)
    nan_rows = df[df[col].isna()]
    print("ก่อนเติมค่า:")
    print(nan_rows[[col]])

    # เติมค่าด้วย mode
    mode_val = df[col].mode()[0]
    df[col].fillna(mode_val, inplace=True)
    print(f"เติมค่า = {mode_val}")

    # แสดงหลังเติม (เฉพาะแถวเดิมที่เคย NaN)
    print("หลังเติมค่า:")
    print(df.loc[nan_rows.index, [col]])
    print("\n")

 คอลัมน์: เพศ
ก่อนเติมค่า:
    เพศ
10  NaN
19  NaN
เติมค่า = ชาย
หลังเติมค่า:
    เพศ
10  ชาย
19  ชาย


 คอลัมน์: คณะ
ก่อนเติมค่า:
    คณะ
10  NaN
17  NaN
เติมค่า = Science
หลังเติมค่า:
        คณะ
10  Science
17  Science

/tmp/ipython-input-1442283714.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(mode_val, inplace=True)
/tmp/ipython-input-1442283714.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(mode_val, inplace=True)

In [99]:
# ลบแถวที่ชื่อเป็น NaN เพราะชื่อไม่ควรหาย
df.dropna(subset=['ชื่อ'], inplace=True)
df.reset_index(drop=True, inplace=True)
print("หลังลบ (เหลือ 18 คน):")

หลังลบ (เหลือ 18 คน):

In [100]:
# ทำให้ชื่อคณะเป็นมาตรฐานเดียวกัน
def standardize_faculty(name):
    if name in ['วิทยาศาสตร์', 'วิทย์', 'Science', 'คณะวิทยาศาสตร์','Sci']:
        return 'วิทยาศาสตร์'
    elif name in ['ศิลปศาสตร์', 'ศิลป์', 'Arts','Liberal Arts']:
        return 'ศิลปศาสตร์'
    else:
        return 'วิศวกรรมศาสตร์'
df['คณะ'] = df['คณะ'].apply(standardize_faculty)

In [101]:
#  ทำให้เพศเป็นมาตรฐานเดียวกัน
def standardize_gender(gender):
    if gender in ['ชาย', 'ช', 'M', 'Male']:
        return 'ชาย'
    elif gender in ['หญิง', 'ญ', 'F', 'Female']:
        return 'หญิง'
    else:
        return 'อื่นๆ'

df['เพศ'] = df['เพศ'].apply(standardize_gender)

In [102]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-06
1,64002,สมหญิง,21.0,หญิง,วิทยาศาสตร์,3.45,165.0,58.0,20.0,2024-01-01
2,64004,สมศักดิ์,22.0,ชาย,วิทยาศาสตร์,3.45,168.0,70.0,10.0,2023-12-17
3,64005,สมใจ,19.0,หญิง,วิศวกรรมศาสตร์,3.89,160.0,52.0,30.0,2024-01-04
4,64006,กานต์,21.0,ชาย,วิศวกรรมศาสตร์,3.12,172.0,75.0,12.0,2024-01-26
5,64007,กิตติ,21.0,หญิง,วิศวกรรมศาสตร์,3.45,158.0,48.0,35.0,2024-02-05
6,64008,จิรา,20.0,หญิง,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2023-12-24
7,64009,ชนาธิป,23.0,ชาย,ศิลปศาสตร์,3.34,163.0,55.0,22.0,2024-02-13
8,64010,ดารา,21.0,หญิง,ศิลปศาสตร์,3.56,167.0,60.0,28.0,2024-01-15
9,64011,ธีระ,21.0,ชาย,วิทยาศาสตร์,3.78,168.0,68.0,21.5,2024-01-23
10,64012,นภา,22.0,ชาย,วิทยาศาสตร์,3.45,171.0,63.0,16.0,2023-12-28
11,64013,บุญมี,20.0,หญิง,วิศวกรรมศาสตร์,3.23,169.0,72.0,24.0,2023-12-22
12,64014,ปรีชา,21.0,ชาย,ศิลปศาสตร์,3.45,164.0,54.0,19.0,2023-12-24
13,64015,พิมพ์,22.0,หญิง,วิทยาศาสตร์,3.67,162.0,56.0,26.0,2024-02-02
14,64016,ภูมิ,19.0,ชาย,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-17
15,64017,มานี,20.0,หญิง,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-18
16,64018,ยุพา,21.0,หญิง,วิทยาศาสตร์,3.23,161.0,50.0,27.0,2024-01-12
17,64019,รัตนา,21.0,ชาย,ศิลปศาสตร์,3.45,174.0,76.0,21.5,2024-01-16
18,64020,ลัดดา,22.0,ชาย,วิทยาศาสตร์,3.45,168.0,64.0,23.0,2024-02-12

In [103]:
# ทำ One-Hot Encoding และกำหนด dtype เป็น int
df_encoded = pd.get_dummies(df, columns=['คณะ'], dtype=int)

# แสดงผลลัพธ์
print(df_encoded.head())

   รหัสนักศึกษา      ชื่อ  อายุ   เพศ   GPA  ส่วนสูง_cm  น้ำหนัก_kg  \
0         64001     สมชาย  20.0   ชาย  3.21       170.0        65.0
1         64002    สมหญิง  21.0  หญิง  3.45       165.0        58.0
2         64004  สมศักดิ์  22.0   ชาย  3.45       168.0        70.0
3         64005      สมใจ  19.0  หญิง  3.89       160.0        52.0
4         64006     กานต์  21.0   ชาย  3.12       172.0        75.0

   ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน  คณะ_วิทยาศาสตร์  \
0                     15.0      2024-01-06                1
1                     20.0      2024-01-01                1
2                     10.0      2023-12-17                1
3                     30.0      2024-01-04                0
4                     12.0      2024-01-26                0

   คณะ_วิศวกรรมศาสตร์  คณะ_ศิลปศาสตร์
0                   0               0
1                   0               0
2                   0               0
3                   1               0
4                   1               0

In [104]:
# สร้าง Features ใหม่จากวันที่ลงทะเบียน
df['ปีที่ลงทะเบียน'] = df['วันที่ลงทะเบียน'].dt.year
df['เดือนที่ลงทะเบียน'] = df['วันที่ลงทะเบียน'].dt.month
df['วันในสัปดาห์ที่ลงทะเบียน'] = df['วันที่ลงทะเบียน'].dt.day_name()
df['วันในสัปดาห์ที่ลงทะเบียน_ตัวเลข'] = df['วันที่ลงทะเบียน'].dt.weekday
df['ช่วงเวลาลงทะเบียนในเดือน'] = pd.cut(df['วันที่ลงทะเบียน'].dt.day,
                                         bins=[0, 10, 20, 31],
                                         labels=['ต้นเดือน', 'กลางเดือน', 'ปลายเดือน'])

# แสดงผลลัพธ์
print(df[['วันที่ลงทะเบียน',
          'ปีที่ลงทะเบียน',
          'เดือนที่ลงทะเบียน',
          'วันในสัปดาห์ที่ลงทะเบียน_ตัวเลข',
          'ช่วงเวลาลงทะเบียนในเดือน']].head())

  วันที่ลงทะเบียน  ปีที่ลงทะเบียน  เดือนที่ลงทะเบียน  \
0      2024-01-06            2024                  1
1      2024-01-01            2024                  1
2      2023-12-17            2023                 12
3      2024-01-04            2024                  1
4      2024-01-26            2024                  1

   วันในสัปดาห์ที่ลงทะเบียน_ตัวเลข ช่วงเวลาลงทะเบียนในเดือน
0                                5                 ต้นเดือน
1                                0                 ต้นเดือน
2                                6                กลางเดือน
3                                3                 ต้นเดือน
4                                4                ปลายเดือน

In [105]:
#การรวม Features
#สร้าง BMI และ สถานะสุขภาพ
df['BMI'] = df['น้ำหนัก_kg'] / (df['ส่วนสูง_cm'] / 100)**2
df['สถานะสุขภาพ'] = pd.cut(df['BMI'],
                            bins=[0, 18.5, 25, 30, 100],
                            labels=['ผอม', 'ปกติ', 'อ้วน', 'อ้วนมาก'])

# แสดงผลลัพธ์
print(df[['ชื่อ', 'ส่วนสูง_cm', 'น้ำหนัก_kg', 'BMI', 'สถานะสุขภาพ']].head())

       ชื่อ  ส่วนสูง_cm  น้ำหนัก_kg        BMI สถานะสุขภาพ
0     สมชาย       170.0        65.0  22.491349        ปกติ
1    สมหญิง       165.0        58.0  21.303949        ปกติ
2  สมศักดิ์       168.0        70.0  24.801587        ปกติ
3      สมใจ       160.0        52.0  20.312500        ปกติ
4     กานต์       172.0        75.0  25.351541        อ้วน